post http://localhost:3001/users/
Content-Type:application/json 

{
  "username": "aaaaaaa",
  "name": "Ganesh",
  "password": "Ganesh123",
  "gender": "male",
  "location": "Detroit"
} 


###

post http://localhost:3000/login
Content-Type:application/json  

{
  "username": "adam_richard",
  "password": "richard_567"
}

###
put http://localhost:3000/change-password

Content-Type:application/json  

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}
