post http://localhost:3001/users/
Content-Type:application/json 

{
  "username": "tester",
  "name": "Ganesh",
  "password": "test123",
  "gender": "male",
  "location": "Detroit"
} 


###

post http://localhost:3001/login
Content-Type:application/json  

{
  "username": "tester",
  "password": "test123"
} 

###
put http://localhost:3000/change-password

Content-Type:application/json  

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}
